### ISSUE TITLE
Unable to open the power point presentation

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/Orchard-Harvest-Speaker-Toolbox#2]
I tried to download the power point presentation. For some reason my anivirus prevents me from opening it. 

I tried to open the file using online editor and it also fails.

**Comment by Piedone** [comment]
Please be more specific, because I have no issue with it after downloading the raw file from here: https://github.com/OrchardCMS/Orchard-Harvest-Speaker-Toolbox/blob/main/Orchard%20Harvest%202024%20presentation%20template.pptx (nor when cloning the repo). How does it fail?

Antivirus software can blanket prevent downloaded Office files from being opened, but you should be able to override that for each file.

**Comment by MikeAlhayek** [comment]
When I downloaded the file directly from GitHub it had the error. I cloned the repo and the files worked.
